with-expecter: True
disable-version-string: True
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName }}Mock"
dir: "mocks"
outpkg: "mocks"
packages:
  github.com/g-villarinho/flash-buy-api/clients:
    config:
      all: True
      recursive: True
  github.com/g-villarinho/flash-buy-api/handlers:
    config:
      all: True
      recursive: True
  github.com/g-villarinho/flash-buy-api/services:
    config:
      all: True
      recursive: True
  github.com/g-villarinho/flash-buy-api/repositories:
    config:
      all: True
      recursive: True
  github.com/g-villarinho/flash-buy-api/storages:
    config:
      all: True
      recursive: True
  github.com/g-villarinho/flash-buy-api/pkgs:
    config:
      all: True
      recursive: True
  github.com/g-villarinho/flash-buy-api/notifications:
    config:
      all: True
      recursive: True
