with-expecter: True
disable-version-string: True
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName }}Mock"
dir: "mocks"
outpkg: "mocks"
packages:
    github.com/g-villarinho/xp-life-api/clients:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/xp-life-api/handlers:
            config:
                all: True
                recursive: True
    github.com/g-villarinho/xp-life-api/services:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/xp-life-api/repositories:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/xp-life-api/storages:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/xp-life-api/pkgs:
        config:
            all: True
            recursive: True
    github.com/g-villarinho/xp-life-api/notifications:
        config:
            all: True
            recursive: True